# SSL/TLS configuration
#
# SSL/TLS will only be configured if `apache_ssl_certs` and `apache_ssl_key`
# are supplied.
#
---
- name: 'create ssl directory'
  file:
    path: '/etc/apache2/ssl'
    state: '{{ (apache_ssl_certs != "" or apache_ssl_key != "") | ternary("directory", "absent") }}'
    owner: 'root'
    group: 'root'
    mode: '0700'

- name: 'deploy SSL public certificate'
  when: apache_ssl_certs != ''
  copy:
    content: '{{ apache_ssl_certs }}'
    dest: '/etc/apache2/ssl/cert.pem'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'deploy SSL private key'
  when: apache_ssl_key != ''
  copy:
    content: '{{ apache_ssl_key }}'
    dest: '/etc/apache2/ssl/key.pem'
    owner: 'root'
    group: 'root'
    mode: '0600'
  no_log: true

- name: 'create SSL site configuration'
  when: apache_ssl_certs != '' and apache_ssl_key != ''
  template:
    src: 'local-ssl-site.conf.j2'
    dest: '/etc/apache2/sites-available/local-ssl-site.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    - 'restart Apache service'

- name: 'enable SSL site configuration'
  when: apache_ssl_certs != '' and apache_ssl_key != ''
  file:
    src: '../sites-available/local-ssl-site.conf'
    dest: '/etc/apache2/sites-enabled/local-ssl-site.conf'
    state: 'link'
    owner: 'root'
    group: 'root'
  notify:
    - 'restart Apache service'

- name: 'remove SSL site config'
  when: not (apache_ssl_certs != '' and apache_ssl_key != '')
  file:
    dest: '{{ item }}'
    state: 'absent'
  with_items:
    - '/etc/apache2/sites-enabled/local-ssl-site.conf'
    - '/etc/apache2/sites-available/local-ssl-site.conf'
  notify:
    - 'restart Apache service'

- name: 'enable SSL support'
  apache2_module:
    name:  'ssl'
    state: '{{ (apache_ssl_certs != "" and apache_ssl_key != "") | ternary("present", "absent") }}'
  notify:
   - 'restart Apache service'
