---
apache_hardening_disable_trace: true
apache_hardening_disable_server_signature: true
apache_hardening_enabled: '{{
  apache_hardening_disable_server_signature or
  apache_hardening_disable_trace
}}'

apache_iptables_rules:
 - '-A INPUT -s 192.168.0.0/16 -p tcp -m tcp --dport 80 -m comment --comment "Allow HTTP" -j ACCEPT'
 - '-A INPUT -s 192.168.0.0/16 -p tcp -m tcp --dport 443 -m comment --comment "Allow HTTPS" -j ACCEPT'

apache_site_aliases: []
apache_site_name: '{{ ansible_fqdn }}'

apache_ssl_certs: '{{ ssl_certs | default(None) }}'
apache_ssl_key: '{{ ssl_key | default(None) }}'
